//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class fr
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource.fr", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser.
        /// </summary>
        internal static string resetButton
        {
            get
            {
                return ResourceManager.GetString("resetButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Au sujet de ce médicament.
        /// </summary>
        internal static string sumMedication
        {
            get
            {
                return ResourceManager.GetString("sumMedication", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Microbiologie.
        /// </summary>
        internal static string sumMicrobiology
        {
            get
            {
                return ResourceManager.GetString("sumMicrobiology", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pour de plus amples renseignements.
        /// </summary>
        internal static string sumMoreInfo
        {
            get
            {
                return ResourceManager.GetString("sumMoreInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Surdosage.
        /// </summary>
        internal static string sumOverdosage
        {
            get
            {
                return ResourceManager.GetString("sumOverdosage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pharmacologie détaillée.
        /// </summary>
        internal static string sumPharmacology
        {
            get
            {
                return ResourceManager.GetString("sumPharmacology", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Renseignements pharmaceutiques.
        /// </summary>
        internal static string sumPharmInfo
        {
            get
            {
                return ResourceManager.GetString("sumPharmInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Renseignements sommaires sur le produit.
        /// </summary>
        internal static string sumProdInfo
        {
            get
            {
                return ResourceManager.GetString("sumProdInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Utilisation appropriée de ce médicament.
        /// </summary>
        internal static string sumProperUse
        {
            get
            {
                return ResourceManager.GetString("sumProperUse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Références.
        /// </summary>
        internal static string sumReferences
        {
            get
            {
                return ResourceManager.GetString("sumReferences", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Déclaration des effets indésirables soupçonnés.
        /// </summary>
        internal static string sumReporting
        {
            get
            {
                return ResourceManager.GetString("sumReporting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Procédures à suivre en ce qui concerne les effets secondaires.
        /// </summary>
        internal static string sumSideEffects
        {
            get
            {
                return ResourceManager.GetString("sumSideEffects", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Instructions particulières de manipulation.
        /// </summary>
        internal static string sumSpecialHandling
        {
            get
            {
                return ResourceManager.GetString("sumSpecialHandling", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Entreposage et stabilité.
        /// </summary>
        internal static string sumStorage
        {
            get
            {
                return ResourceManager.GetString("sumStorage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Toxicologie.
        /// </summary>
        internal static string sumToxicology
        {
            get
            {
                return ResourceManager.GetString("sumToxicology", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mises en garde et précautions.
        /// </summary>
        internal static string sumWarnings
        {
            get
            {
                return ResourceManager.GetString("sumWarnings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Symptôme.
        /// </summary>
        internal static string symptom
        {
            get
            {
                return ResourceManager.GetString("symptom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Talk with your doctor in all cases_fr.
        /// </summary>
        internal static string talkwithDocAllCases
        {
            get
            {
                return ResourceManager.GetString("talkwithDocAllCases", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Talk with your doctor only if server_fr.
        /// </summary>
        internal static string talkwithDocIfSever
        {
            get
            {
                return ResourceManager.GetString("talkwithDocIfSever", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string test
        {
            get
            {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Classification thérapeutique.
        /// </summary>
        internal static string therapeuticClassification
        {
            get
            {
                return ResourceManager.GetString("therapeuticClassification", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tmax (h).
        /// </summary>
        internal static string tmax
        {
            get
            {
                return ResourceManager.GetString("tmax", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Toxicologie.
        /// </summary>
        internal static string toxicology
        {
            get
            {
                return ResourceManager.GetString("toxicology", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Peu fréquent.
        /// </summary>
        internal static string uncommon
        {
            get
            {
                return ResourceManager.GetString("uncommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Inconnu.
        /// </summary>
        internal static string unknown
        {
            get
            {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dose habituelle.
        /// </summary>
        internal static string usualDose
        {
            get
            {
                return ResourceManager.GetString("usualDose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usual dose file.
        /// </summary>
        internal static string usualDoseFile
        {
            get
            {
                return ResourceManager.GetString("usualDoseFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Très rare.
        /// </summary>
        internal static string veryRare
        {
            get
            {
                return ResourceManager.GetString("veryRare", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Volume de l’ampoule.
        /// </summary>
        internal static string vialSize
        {
            get
            {
                return ResourceManager.GetString("vialSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Volume de diluant nécessaire par ampoule.
        /// </summary>
        internal static string volumediluent
        {
            get
            {
                return ResourceManager.GetString("volumediluent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Activités (mises en garde et précautions, p. ex. Amoindrissement des facultés)
        ///États actuels (contre-indications, mises en garde et précautions)
        ///Maladies précédentes (contre-indications, mises en garde et précautions)
        ///Questions concernant la reproduction (contre-indications, mises en garde et précautions)
        ///Procédures médicales prévues (mises en garde et précautions)
        ///Allergies quelconques à ce médicament, aux ingrédients ou aux composants du récipient (contre-indications)
        ///.
        /// </summary>
        internal static string warningsInfo
        {
            get
            {
                return ResourceManager.GetString("warningsInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Les formes posologiques sont.
        /// </summary>
        internal static string whatDosageForm
        {
            get
            {
                return ResourceManager.GetString("whatDosageForm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Procédures à suivre en ce qui concerne les effets secondaires.
        /// </summary>
        internal static string whatToDo
        {
            get
            {
                return ResourceManager.GetString("whatToDo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Les circonstances oû il est déconseillé d’utiliser ce médicament.
        /// </summary>
        internal static string whenNotUse
        {
            get
            {
                return ResourceManager.GetString("whenNotUse", resourceCulture);
            }
        }
    }
}
