//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities (Warnings and Precautions, e,g, under Occupational Hazards).
        /// </summary>
        internal static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any allergies to this drug or its ingredients or components of the container (Contraindications).
        /// </summary>
        internal static string Allergy {
            get {
                return ResourceManager.GetString("Allergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyte name.
        /// </summary>
        internal static string AnalyteName {
            get {
                return ResourceManager.GetString("AnalyteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparative bioavailability studies.
        /// </summary>
        internal static string BioStudy {
            get {
                return ResourceManager.GetString("BioStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to •	To load a new blank PM template for the creation of XML file, select a template type from the drop menu, and press the &quot;Load template&quot; button.
        ///            •	To load an existing XML file, press the “Choose File” button (&quot;Browse...&quot; in Internet Explorer and Firefox), select the file and press the &quot;Open&quot; button in the file browser. Press the &quot;Load XML&quot; button.
        ///            •	To save a file, press the &quot;Save draft&quot; button. The file name of the new file will always be &quot;productmonograph&quot; with the &apos;.zip&apos; extensi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to •	Compatible with Mozilla Firefox (recommended) (6 and higher), Internet Explorer (7 to 10), Google chrome (8 and higher) and Apple Safari (4 and higher).
        ///•	To properly view and use this form, your internet browser will need to support HTML5. It&apos;s recommended that your computer have the latest version of one of the more widely used internet web browsers.
        ///•	You can navigate the form using any mobile device (such as a tablet or a smart phone). The information displayed will be adapted for your device.
        ///•	No [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BottomBody {
            get {
                return ResourceManager.GetString("BottomBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append Column.
        /// </summary>
        internal static string btnAddCol {
            get {
                return ResourceManager.GetString("btnAddCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string btnAddExtraContraindications {
            get {
                return ResourceManager.GetString("btnAddExtraContraindications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append row.
        /// </summary>
        internal static string btnAppendRow {
            get {
                return ResourceManager.GetString("btnAppendRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply symbol.
        /// </summary>
        internal static string btnApplySumbol {
            get {
                return ResourceManager.GetString("btnApplySumbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove last column.
        /// </summary>
        internal static string btnDelCol {
            get {
                return ResourceManager.GetString("btnDelCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete row.
        /// </summary>
        internal static string btnDeleteRow {
            get {
                return ResourceManager.GetString("btnDeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Symbol.
        /// </summary>
        internal static string btnlblApplySymbol {
            get {
                return ResourceManager.GetString("btnlblApplySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load template.
        /// </summary>
        internal static string btnLoadTemplate {
            get {
                return ResourceManager.GetString("btnLoadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string btnRemoveVal {
            get {
                return ResourceManager.GetString("btnRemoveVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save draft.
        /// </summary>
        internal static string btnSaveDraft {
            get {
                return ResourceManager.GetString("btnSaveDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please save your form data in a draft file..
        /// </summary>
        internal static string btnSaveDraft_tooltip {
            get {
                return ResourceManager.GetString("btnSaveDraft_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemical name.
        /// </summary>
        internal static string Chemicalname {
            get {
                return ResourceManager.GetString("Chemicalname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinica trials:.
        /// </summary>
        internal static string ClinicalTrials {
            get {
                return ResourceManager.GetString("ClinicalTrials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a complete list of side effects.  For any unexpected effects while taking.
        /// </summary>
        internal static string Comment1 {
            get {
                return ResourceManager.GetString("Comment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , contact your doctor or pharmacist..
        /// </summary>
        internal static string Comment2 {
            get {
                return ResourceManager.GetString("Comment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current conditions (Contraindications, Warnings and Precautions).
        /// </summary>
        internal static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence interval.
        /// </summary>
        internal static string ConfInter {
            get {
                return ResourceManager.GetString("ConfInter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover page.
        /// </summary>
        internal static string CoverPage {
            get {
                return ResourceManager.GetString("CoverPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed pharmacology:.
        /// </summary>
        internal static string DetailedPharma {
            get {
                return ResourceManager.GetString("DetailedPharma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past diseases (Contraindications, Warnings and Precautions).
        /// </summary>
        internal static string Diseases {
            get {
                return ResourceManager.GetString("Diseases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What dosage forms it comes in:.
        /// </summary>
        internal static string DosageForm {
            get {
                return ResourceManager.GetString("DosageForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug substance.
        /// </summary>
        internal static string DrugSub {
            get {
                return ResourceManager.GetString("DrugSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footnote.
        /// </summary>
        internal static string footnote {
            get {
                return ResourceManager.GetString("footnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactions with this medication.
        /// </summary>
        internal static string Interactions {
            get {
                return ResourceManager.GetString("Interactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reproductive issues (Contraindications, Warnings and Precautions).
        /// </summary>
        internal static string Issues {
            get {
                return ResourceManager.GetString("Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last revised:.
        /// </summary>
        internal static string LastRevised {
            get {
                return ResourceManager.GetString("LastRevised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string lblAdministration {
            get {
                return ResourceManager.GetString("lblAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adverse drug reaction overview.
        /// </summary>
        internal static string lblAdverse {
            get {
                return ResourceManager.GetString("lblAdverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and / or.
        /// </summary>
        internal static string lblAndOr {
            get {
                return ResourceManager.GetString("lblAndOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any specific precautions, storage periods and incompatibilities.
        /// </summary>
        internal static string lblAnySpecific {
            get {
                return ResourceManager.GetString("lblAnySpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approximate available volume.
        /// </summary>
        internal static string lblApproximate {
            get {
                return ResourceManager.GetString("lblApproximate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand name.
        /// </summary>
        internal static string lblBrandName {
            get {
                return ResourceManager.GetString("lblBrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraindications.
        /// </summary>
        internal static string lblContraindications {
            get {
                return ResourceManager.GetString("lblContraindications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of preparation.
        /// </summary>
        internal static string lblDateOfPreparation {
            get {
                return ResourceManager.GetString("lblDateOfPreparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of revision.
        /// </summary>
        internal static string lblDateOfRevision {
            get {
                return ResourceManager.GetString("lblDateOfRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage form.
        /// </summary>
        internal static string lblDosageForm2 {
            get {
                return ResourceManager.GetString("lblDosageForm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage forms, composition and packaging.
        /// </summary>
        internal static string lblDosageForms {
            get {
                return ResourceManager.GetString("lblDosageForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosing considerations.
        /// </summary>
        internal static string lblDosing {
            get {
                return ResourceManager.GetString("lblDosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose an xml file..
        /// </summary>
        internal static string lblErr_PlsChooseXML {
            get {
                return ResourceManager.GetString("lblErr_PlsChooseXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For management of a suspected drug overdose, contact your regional Poison Control For management of a suspected drug overdose, contact your regional Poison Control Centre.
        /// </summary>
        internal static string lblForManagement {
            get {
                return ResourceManager.GetString("lblForManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geriatrics.
        /// </summary>
        internal static string lblGeriatrics {
            get {
                return ResourceManager.GetString("lblGeriatrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headings.
        /// </summary>
        internal static string lblHeadings {
            get {
                return ResourceManager.GetString("lblHeadings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proper name is indicated for:.
        /// </summary>
        internal static string lblICProperName {
            get {
                return ResourceManager.GetString("lblICProperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinically relevant nonmedicinal ingredients.
        /// </summary>
        internal static string lblIngredients {
            get {
                return ResourceManager.GetString("lblIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To load a new blank PM template for the creation of XML file, select a template type from the drop menu, and press the &quot;Load template&quot; button..
        /// </summary>
        internal static string lblLoadTemplateInst {
            get {
                return ResourceManager.GetString("lblLoadTemplateInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load XML file.
        /// </summary>
        internal static string lblLoadXML {
            get {
                return ResourceManager.GetString("lblLoadXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To load an existing XML file, press the “Choose File” button (&quot;Browse...&quot; in Internet Explorer and Firefox), select the file and press the &quot;Open&quot; button in the file browser. Press the &quot;Load XML&quot; button..
        /// </summary>
        internal static string lblLoadXmlInst {
            get {
                return ResourceManager.GetString("lblLoadXmlInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanism of action.
        /// </summary>
        internal static string lblMechanism {
            get {
                return ResourceManager.GetString("lblMechanism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed dose.
        /// </summary>
        internal static string lblMissed {
            get {
                return ResourceManager.GetString("lblMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal concentration per mL.
        /// </summary>
        internal static string lblNominal {
            get {
                return ResourceManager.GetString("lblNominal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oral solutions.
        /// </summary>
        internal static string lblOral {
            get {
                return ResourceManager.GetString("lblOral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string lblOverview {
            get {
                return ResourceManager.GetString("lblOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parenteral products:.
        /// </summary>
        internal static string lblParenteralProducts {
            get {
                return ResourceManager.GetString("lblParenteralProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part I: Health professional information.
        /// </summary>
        internal static string lblPartITitle {
            get {
                return ResourceManager.GetString("lblPartITitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pediatrics.
        /// </summary>
        internal static string lblPediatrics {
            get {
                return ResourceManager.GetString("lblPediatrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacodynamics.
        /// </summary>
        internal static string lblPharmacodynamics {
            get {
                return ResourceManager.GetString("lblPharmacodynamics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proper name.
        /// </summary>
        internal static string lblProperName {
            get {
                return ResourceManager.GetString("lblProperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended dose and dosage adjustment.
        /// </summary>
        internal static string lblRecommended {
            get {
                return ResourceManager.GetString("lblRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconstitution.
        /// </summary>
        internal static string lblReconstitution {
            get {
                return ResourceManager.GetString("lblReconstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route of administration.
        /// </summary>
        internal static string lblRouteOfAdministration {
            get {
                return ResourceManager.GetString("lblRouteOfAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduling symbol.
        /// </summary>
        internal static string lblSchedulingSymbol {
            get {
                return ResourceManager.GetString("lblSchedulingSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a template:.
        /// </summary>
        internal static string lblSelectTemplate {
            get {
                return ResourceManager.GetString("lblSelectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serious warnings and precautions.
        /// </summary>
        internal static string lblSerious {
            get {
                return ResourceManager.GetString("lblSerious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special handling instruction.
        /// </summary>
        internal static string lblSpecialHandling {
            get {
                return ResourceManager.GetString("lblSpecialHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor address.
        /// </summary>
        internal static string lblSponsorAddress {
            get {
                return ResourceManager.GetString("lblSponsorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor name.
        /// </summary>
        internal static string lblSponsorName {
            get {
                return ResourceManager.GetString("lblSponsorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage and stability.
        /// </summary>
        internal static string lblStorage {
            get {
                return ResourceManager.GetString("lblStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength per dosage.
        /// </summary>
        internal static string lblStrengthperDosage {
            get {
                return ResourceManager.GetString("lblStrengthperDosage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vial size.
        /// </summary>
        internal static string lblVialSize {
            get {
                return ResourceManager.GetString("lblVialSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume of diluent to be added to vial.
        /// </summary>
        internal static string lblVolume {
            get {
                return ResourceManager.GetString("lblVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years of age .
        /// </summary>
        internal static string lblYearsOfAge {
            get {
                return ResourceManager.GetString("lblYearsOfAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years of age.
        /// </summary>
        internal static string lblYearsOfAge2 {
            get {
                return ResourceManager.GetString("lblYearsOfAge2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years of age or.
        /// </summary>
        internal static string lblYearsOfAgeOr {
            get {
                return ResourceManager.GetString("lblYearsOfAgeOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this medication.
        /// </summary>
        internal static string Medication {
            get {
                return ResourceManager.GetString("Medication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When it should not be used:.
        /// </summary>
        internal static string MedicationNotUsed {
            get {
                return ResourceManager.GetString("MedicationNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What the medication is used for:.
        /// </summary>
        internal static string MedicationUse {
            get {
                return ResourceManager.GetString("MedicationUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What the medicinal ingredient is:.
        /// </summary>
        internal static string MedIngredient {
            get {
                return ResourceManager.GetString("MedIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microbiology:.
        /// </summary>
        internal static string Microbiology {
            get {
                return ResourceManager.GetString("Microbiology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed dose:.
        /// </summary>
        internal static string MissedDose {
            get {
                return ResourceManager.GetString("MissedDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molecular formula.
        /// </summary>
        internal static string Molecularformula {
            get {
                return ResourceManager.GetString("Molecularformula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molecular mass.
        /// </summary>
        internal static string Molecularmass {
            get {
                return ResourceManager.GetString("Molecularmass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information:.
        /// </summary>
        internal static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What the nonmedicinal ingredients are:.
        /// </summary>
        internal static string NonMedicinalIng {
            get {
                return ResourceManager.GetString("NonMedicinalIng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity of the test product..
        /// </summary>
        internal static string Note1 {
            get {
                return ResourceManager.GetString("Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity of the reference product, including the manufacturer, and origin (country of purchase)..
        /// </summary>
        internal static string Note2 {
            get {
                return ResourceManager.GetString("Note2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For drugs with a half-life greater than 24 hours AUCT should be replaced with AUC0-72..
        /// </summary>
        internal static string Note3 {
            get {
                return ResourceManager.GetString("Note3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expressed as either the arithmetic mean (CV%) or the median (range) only..
        /// </summary>
        internal static string Note4 {
            get {
                return ResourceManager.GetString("Note4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expressed as the arithmetic mean (CV%) only..
        /// </summary>
        internal static string Note5 {
            get {
                return ResourceManager.GetString("Note5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate % Confidence Interval (i.e., 90% or 95%) in the column heading and list for the AUCT, AUCI and CMAX (if required)..
        /// </summary>
        internal static string Note6 {
            get {
                return ResourceManager.GetString("Note6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over dose:.
        /// </summary>
        internal static string OverDose {
            get {
                return ResourceManager.GetString("OverDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part II:  Scientific information.
        /// </summary>
        internal static string PartII {
            get {
                return ResourceManager.GetString("PartII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part III: Consumer information.
        /// </summary>
        internal static string PartIII {
            get {
                return ResourceManager.GetString("PartIII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmaceutical standard.
        /// </summary>
        internal static string PharmaceuticalStandard {
            get {
                return ResourceManager.GetString("PharmaceuticalStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physicochemical properties.
        /// </summary>
        internal static string Physicochemicalproperties {
            get {
                return ResourceManager.GetString("Physicochemicalproperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point form:.
        /// </summary>
        internal static string PointForm {
            get {
                return ResourceManager.GetString("PointForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anticipated medical procedures (Warnings and precautions).
        /// </summary>
        internal static string Procedure {
            get {
                return ResourceManager.GetString("Procedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proper Name.
        /// </summary>
        internal static string ProperNameMI {
            get {
                return ResourceManager.GetString("ProperNameMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proper use of this medication.
        /// </summary>
        internal static string ProperUse {
            get {
                return ResourceManager.GetString("ProperUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        internal static string Rare {
            get {
                return ResourceManager.GetString("Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References:.
        /// </summary>
        internal static string References {
            get {
                return ResourceManager.GetString("References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting suspected side effects.
        /// </summary>
        internal static string Reporting {
            get {
                return ResourceManager.GetString("Reporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio of geometric means.
        /// </summary>
        internal static string RGM {
            get {
                return ResourceManager.GetString("RGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serious side effects, how often they happen and what to do about them.
        /// </summary>
        internal static string SeriousSideEffect {
            get {
                return ResourceManager.GetString("SeriousSideEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serious warnings and precautions.
        /// </summary>
        internal static string SeriousWarning {
            get {
                return ResourceManager.GetString("SeriousWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side effects and what to do about them:.
        /// </summary>
        internal static string SideEffect {
            get {
                return ResourceManager.GetString("SideEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side effects what to do:.
        /// </summary>
        internal static string SideEffectsWhatToDo {
            get {
                return ResourceManager.GetString("SideEffectsWhatToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to store it:.
        /// </summary>
        internal static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structural formula.
        /// </summary>
        internal static string Structuralformula {
            get {
                return ResourceManager.GetString("Structuralformula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form instructions.
        /// </summary>
        internal static string subMenuItem1 {
            get {
                return ResourceManager.GetString("subMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to the main page of DHPR form with form Instruction.
        /// </summary>
        internal static string subMenuItem1_tooltip {
            get {
                return ResourceManager.GetString("subMenuItem1_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover page.
        /// </summary>
        internal static string subMenuItem2 {
            get {
                return ResourceManager.GetString("subMenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part I.
        /// </summary>
        internal static string subMenuItem3 {
            get {
                return ResourceManager.GetString("subMenuItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part II.
        /// </summary>
        internal static string subMenuItem4 {
            get {
                return ResourceManager.GetString("subMenuItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part III.
        /// </summary>
        internal static string subMenuItem5 {
            get {
                return ResourceManager.GetString("subMenuItem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission control No.
        /// </summary>
        internal static string SubmissionControlNo {
            get {
                return ResourceManager.GetString("SubmissionControlNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinical Trials.
        /// </summary>
        internal static string SumCT {
            get {
                return ResourceManager.GetString("SumCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactions with this medication.
        /// </summary>
        internal static string SumInteractions {
            get {
                return ResourceManager.GetString("SumInteractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microbiology.
        /// </summary>
        internal static string SumMicrobiology {
            get {
                return ResourceManager.GetString("SumMicrobiology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information.
        /// </summary>
        internal static string SumMoreInfo {
            get {
                return ResourceManager.GetString("SumMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed pharmacology.
        /// </summary>
        internal static string SumPharmacology {
            get {
                return ResourceManager.GetString("SumPharmacology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmaceutical information.
        /// </summary>
        internal static string SumPharmInfo {
            get {
                return ResourceManager.GetString("SumPharmInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proper use of this medication.
        /// </summary>
        internal static string SumProperUse {
            get {
                return ResourceManager.GetString("SumProperUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        internal static string SumRef {
            get {
                return ResourceManager.GetString("SumRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting suspected side effects.
        /// </summary>
        internal static string SumReporting {
            get {
                return ResourceManager.GetString("SumReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side effects and what to do about them.
        /// </summary>
        internal static string SumSideEffect {
            get {
                return ResourceManager.GetString("SumSideEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to store it.
        /// </summary>
        internal static string SumStore {
            get {
                return ResourceManager.GetString("SumStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary product information.
        /// </summary>
        internal static string SumSummaryProductInformation {
            get {
                return ResourceManager.GetString("SumSummaryProductInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toxicology.
        /// </summary>
        internal static string SumToxicology {
            get {
                return ResourceManager.GetString("SumToxicology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings and precautions.
        /// </summary>
        internal static string SumWarningsPrecautions {
            get {
                return ResourceManager.GetString("SumWarningsPrecautions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action and clinical pharmacology.
        /// </summary>
        internal static string SUM_ACTION {
            get {
                return ResourceManager.GetString("SUM_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adverse reactions.
        /// </summary>
        internal static string SUM_ADVERSE {
            get {
                return ResourceManager.GetString("SUM_ADVERSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraindications.
        /// </summary>
        internal static string SUM_CONTRAINDICATIONS {
            get {
                return ResourceManager.GetString("SUM_CONTRAINDICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage and administration.
        /// </summary>
        internal static string SUM_DOSAGE {
            get {
                return ResourceManager.GetString("SUM_DOSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage forms, composition and packaging.
        /// </summary>
        internal static string SUM_DOSAGEFORMS {
            get {
                return ResourceManager.GetString("SUM_DOSAGEFORMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug interations.
        /// </summary>
        internal static string SUM_DRUG_INTERACTIONS {
            get {
                return ResourceManager.GetString("SUM_DRUG_INTERACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indications and clinical use.
        /// </summary>
        internal static string SUM_INDICATIONS {
            get {
                return ResourceManager.GetString("SUM_INDICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdosage.
        /// </summary>
        internal static string SUM_OVERDOSAGE {
            get {
                return ResourceManager.GetString("SUM_OVERDOSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special handling instruction.
        /// </summary>
        internal static string SUM_SPECIAL_HANDLING {
            get {
                return ResourceManager.GetString("SUM_SPECIAL_HANDLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage and stability.
        /// </summary>
        internal static string SUM_STORAGE {
            get {
                return ResourceManager.GetString("SUM_STORAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings and precaution.
        /// </summary>
        internal static string SUM_WARNINGS {
            get {
                return ResourceManager.GetString("SUM_WARNINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptom.
        /// </summary>
        internal static string Symptom {
            get {
                return ResourceManager.GetString("Symptom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand name.
        /// </summary>
        internal static string tbBName {
            get {
                return ResourceManager.GetString("tbBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage form.
        /// </summary>
        internal static string tbDForm {
            get {
                return ResourceManager.GetString("tbDForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmaceutical standard (if applicable).
        /// </summary>
        internal static string tbPharmaceuticalStandard {
            get {
                return ResourceManager.GetString("tbPharmaceuticalStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proper name.
        /// </summary>
        internal static string tbPName {
            get {
                return ResourceManager.GetString("tbPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string tbStrength {
            get {
                return ResourceManager.GetString("tbStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string tbSUnit {
            get {
                return ResourceManager.GetString("tbSUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string tbSValue {
            get {
                return ResourceManager.GetString("tbSValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Therapeutic classification.
        /// </summary>
        internal static string tbTherapeuticClassifications {
            get {
                return ResourceManager.GetString("tbTherapeuticClassifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical specifications.
        /// </summary>
        internal static string TechnicalSpecs {
            get {
                return ResourceManager.GetString("TechnicalSpecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Therapeutic classification.
        /// </summary>
        internal static string TherapeuticClassification {
            get {
                return ResourceManager.GetString("TherapeuticClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug and health product register - product monograph form.
        /// </summary>
        internal static string TitleForm {
            get {
                return ResourceManager.GetString("TitleForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form instructions.
        /// </summary>
        internal static string TitleFormInstructions {
            get {
                return ResourceManager.GetString("TitleFormInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toxicology:.
        /// </summary>
        internal static string Toxicology {
            get {
                return ResourceManager.GetString("Toxicology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncommon.
        /// </summary>
        internal static string Uncommon {
            get {
                return ResourceManager.GetString("Uncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unkown.
        /// </summary>
        internal static string Unkown {
            get {
                return ResourceManager.GetString("Unkown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the XML product monograph (PM) web form.
        /// </summary>
        internal static string UsingXMLPM {
            get {
                return ResourceManager.GetString("UsingXMLPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usual dose:.
        /// </summary>
        internal static string UsualDose {
            get {
                return ResourceManager.GetString("UsualDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very rare.
        /// </summary>
        internal static string VeryRare {
            get {
                return ResourceManager.GetString("VeryRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What it does:.
        /// </summary>
        internal static string WhatDoes {
            get {
                return ResourceManager.GetString("WhatDoes", resourceCulture);
            }
        }
    }
}
