//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities (Warnings and Precautions, e,g, under Occupational Hazards).
        /// </summary>
        internal static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any allergies to this drug or its ingredients or components of the container (Contraindications).
        /// </summary>
        internal static string Allergy {
            get {
                return ResourceManager.GetString("Allergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyte name.
        /// </summary>
        internal static string AnalyteName {
            get {
                return ResourceManager.GetString("AnalyteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparative bioavailability studies.
        /// </summary>
        internal static string BioStudy {
            get {
                return ResourceManager.GetString("BioStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to •	To load a new blank PM template for the creation of XML file, select a template type from the drop menu, and press the &quot;Load template&quot; button.
        ///            •	To load an existing XML file, press the “Choose File” button (&quot;Browse...&quot; in Internet Explorer and Firefox), select the file and press the &quot;Open&quot; button in the file browser. Press the &quot;Load XML&quot; button.
        ///            •	To save a file, press the &quot;Save draft&quot; button. The file name of the new file will always be &quot;productmonograph&quot; with the &apos;.zip&apos; extensi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to •	Compatible with Mozilla Firefox (recommended) (6 and higher), Internet Explorer (7 to 10), Google chrome (8 and higher) and Apple Safari (4 and higher).
        ///•	To properly view and use this form, your internet browser will need to support HTML5. It&apos;s recommended that your computer have the latest version of one of the more widely used internet web browsers.
        ///•	You can navigate the form using any mobile device (such as a tablet or a smart phone). The information displayed will be adapted for your device.
        ///•	No [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BottomBody {
            get {
                return ResourceManager.GetString("BottomBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemical name.
        /// </summary>
        internal static string Chemicalname {
            get {
                return ResourceManager.GetString("Chemicalname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinica trials:.
        /// </summary>
        internal static string ClinicalTrials {
            get {
                return ResourceManager.GetString("ClinicalTrials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a complete list of side effects.  For any unexpected effects while taking.
        /// </summary>
        internal static string Comment1 {
            get {
                return ResourceManager.GetString("Comment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , contact your doctor or pharmacist..
        /// </summary>
        internal static string Comment2 {
            get {
                return ResourceManager.GetString("Comment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current conditions (Contraindications, Warnings and Precautions).
        /// </summary>
        internal static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence interval.
        /// </summary>
        internal static string ConfInter {
            get {
                return ResourceManager.GetString("ConfInter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed pharmacology:.
        /// </summary>
        internal static string DetailedPharma {
            get {
                return ResourceManager.GetString("DetailedPharma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past diseases (Contraindications, Warnings and Precautions).
        /// </summary>
        internal static string Diseases {
            get {
                return ResourceManager.GetString("Diseases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What dosage forms it comes in:.
        /// </summary>
        internal static string DosageForm {
            get {
                return ResourceManager.GetString("DosageForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug substance.
        /// </summary>
        internal static string DrugSub {
            get {
                return ResourceManager.GetString("DrugSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactions with this medication.
        /// </summary>
        internal static string Interactions {
            get {
                return ResourceManager.GetString("Interactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reproductive issues (Contraindications, Warnings and Precautions).
        /// </summary>
        internal static string Issues {
            get {
                return ResourceManager.GetString("Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last revised:.
        /// </summary>
        internal static string LastRevised {
            get {
                return ResourceManager.GetString("LastRevised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this medication.
        /// </summary>
        internal static string Medication {
            get {
                return ResourceManager.GetString("Medication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When it should not be used:.
        /// </summary>
        internal static string MedicationNotUsed {
            get {
                return ResourceManager.GetString("MedicationNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What the medication is used for:.
        /// </summary>
        internal static string MedicationUse {
            get {
                return ResourceManager.GetString("MedicationUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What the medicinal ingredient is:.
        /// </summary>
        internal static string MedIngredient {
            get {
                return ResourceManager.GetString("MedIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microbiology:.
        /// </summary>
        internal static string Microbiology {
            get {
                return ResourceManager.GetString("Microbiology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed dose:.
        /// </summary>
        internal static string MissedDose {
            get {
                return ResourceManager.GetString("MissedDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molecular formula.
        /// </summary>
        internal static string Molecularformula {
            get {
                return ResourceManager.GetString("Molecularformula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molecular mass.
        /// </summary>
        internal static string Molecularmass {
            get {
                return ResourceManager.GetString("Molecularmass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information:.
        /// </summary>
        internal static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What the nonmedicinal ingredients are:.
        /// </summary>
        internal static string NonMedicinalIng {
            get {
                return ResourceManager.GetString("NonMedicinalIng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity of the test product..
        /// </summary>
        internal static string Note1 {
            get {
                return ResourceManager.GetString("Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity of the reference product, including the manufacturer, and origin (country of purchase)..
        /// </summary>
        internal static string Note2 {
            get {
                return ResourceManager.GetString("Note2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For drugs with a half-life greater than 24 hours AUCT should be replaced with AUC0-72..
        /// </summary>
        internal static string Note3 {
            get {
                return ResourceManager.GetString("Note3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expressed as either the arithmetic mean (CV%) or the median (range) only..
        /// </summary>
        internal static string Note4 {
            get {
                return ResourceManager.GetString("Note4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expressed as the arithmetic mean (CV%) only..
        /// </summary>
        internal static string Note5 {
            get {
                return ResourceManager.GetString("Note5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate % Confidence Interval (i.e., 90% or 95%) in the column heading and list for the AUCT, AUCI and CMAX (if required)..
        /// </summary>
        internal static string Note6 {
            get {
                return ResourceManager.GetString("Note6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over dose:.
        /// </summary>
        internal static string OverDose {
            get {
                return ResourceManager.GetString("OverDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part II:  Scientific information.
        /// </summary>
        internal static string PartII {
            get {
                return ResourceManager.GetString("PartII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part III: Consumer information.
        /// </summary>
        internal static string PartIII {
            get {
                return ResourceManager.GetString("PartIII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physicochemical properties.
        /// </summary>
        internal static string Physicochemicalproperties {
            get {
                return ResourceManager.GetString("Physicochemicalproperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point form:.
        /// </summary>
        internal static string PointForm {
            get {
                return ResourceManager.GetString("PointForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anticipated medical procedures (Warnings and Precautions).
        /// </summary>
        internal static string Procedure {
            get {
                return ResourceManager.GetString("Procedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proper Name.
        /// </summary>
        internal static string ProperNameMI {
            get {
                return ResourceManager.GetString("ProperNameMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proper use of this medication.
        /// </summary>
        internal static string ProperUse {
            get {
                return ResourceManager.GetString("ProperUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        internal static string Rare {
            get {
                return ResourceManager.GetString("Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References:.
        /// </summary>
        internal static string References {
            get {
                return ResourceManager.GetString("References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting suspected side effects.
        /// </summary>
        internal static string Reporting {
            get {
                return ResourceManager.GetString("Reporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio of geometric means.
        /// </summary>
        internal static string RGM {
            get {
                return ResourceManager.GetString("RGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serious side effects, how often they happen and what to do about them.
        /// </summary>
        internal static string SeriousSideEffect {
            get {
                return ResourceManager.GetString("SeriousSideEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serious warnings and precautions.
        /// </summary>
        internal static string SeriousWarning {
            get {
                return ResourceManager.GetString("SeriousWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side effects and what to do about them:.
        /// </summary>
        internal static string SideEffect {
            get {
                return ResourceManager.GetString("SideEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side effects what to do:.
        /// </summary>
        internal static string SideEffectsWhatToDo {
            get {
                return ResourceManager.GetString("SideEffectsWhatToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to store it:.
        /// </summary>
        internal static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structural formula.
        /// </summary>
        internal static string Structuralformula {
            get {
                return ResourceManager.GetString("Structuralformula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinical Trials.
        /// </summary>
        internal static string SumCT {
            get {
                return ResourceManager.GetString("SumCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactions with this medication.
        /// </summary>
        internal static string SumInteractions {
            get {
                return ResourceManager.GetString("SumInteractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microbiology.
        /// </summary>
        internal static string SumMicrobiology {
            get {
                return ResourceManager.GetString("SumMicrobiology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information.
        /// </summary>
        internal static string SumMoreInfo {
            get {
                return ResourceManager.GetString("SumMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed pharmacology.
        /// </summary>
        internal static string SumPharmacology {
            get {
                return ResourceManager.GetString("SumPharmacology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmaceutical information.
        /// </summary>
        internal static string SumPharmInfo {
            get {
                return ResourceManager.GetString("SumPharmInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proper use of this medication.
        /// </summary>
        internal static string SumProperUse {
            get {
                return ResourceManager.GetString("SumProperUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        internal static string SumRef {
            get {
                return ResourceManager.GetString("SumRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting suspected side effects.
        /// </summary>
        internal static string SumReporting {
            get {
                return ResourceManager.GetString("SumReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side effects and what to do about them.
        /// </summary>
        internal static string SumSideEffect {
            get {
                return ResourceManager.GetString("SumSideEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to store it.
        /// </summary>
        internal static string SumStore {
            get {
                return ResourceManager.GetString("SumStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toxicology.
        /// </summary>
        internal static string SumToxicology {
            get {
                return ResourceManager.GetString("SumToxicology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings and precautions.
        /// </summary>
        internal static string SumWarningsPrecautions {
            get {
                return ResourceManager.GetString("SumWarningsPrecautions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptom.
        /// </summary>
        internal static string Symptom {
            get {
                return ResourceManager.GetString("Symptom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical specifications.
        /// </summary>
        internal static string TechnicalSpecs {
            get {
                return ResourceManager.GetString("TechnicalSpecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug and health product register - product monograph form.
        /// </summary>
        internal static string TitleForm {
            get {
                return ResourceManager.GetString("TitleForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form instructions.
        /// </summary>
        internal static string TitleFormInstructions {
            get {
                return ResourceManager.GetString("TitleFormInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toxicology:.
        /// </summary>
        internal static string Toxicology {
            get {
                return ResourceManager.GetString("Toxicology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncommon.
        /// </summary>
        internal static string Uncommon {
            get {
                return ResourceManager.GetString("Uncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unkown.
        /// </summary>
        internal static string Unkown {
            get {
                return ResourceManager.GetString("Unkown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the XML product monograph (PM) web form.
        /// </summary>
        internal static string UsingXMLPM {
            get {
                return ResourceManager.GetString("UsingXMLPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usual dose:.
        /// </summary>
        internal static string UsualDose {
            get {
                return ResourceManager.GetString("UsualDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very rare.
        /// </summary>
        internal static string VeryRare {
            get {
                return ResourceManager.GetString("VeryRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What it does:.
        /// </summary>
        internal static string WhatDoes {
            get {
                return ResourceManager.GetString("WhatDoes", resourceCulture);
            }
        }
    }
}
