//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to •	To load a new blank PM template for the creation of XML file, select a template type from the drop menu, and press the &quot;Load template&quot; button.
        ///            •	To load an existing XML file, press the “Choose File” button (&quot;Browse...&quot; in Internet Explorer and Firefox), select the file and press the &quot;Open&quot; button in the file browser. Press the &quot;Load XML&quot; button.
        ///            •	To save a file, press the &quot;Save draft&quot; button. The file name of the new file will always be &quot;productmonograph&quot; with the &apos;.zip&apos; extensi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to •	Compatible with Mozilla Firefox (recommended) (6 and higher), Internet Explorer (7 to 10), Google chrome (8 and higher) and Apple Safari (4 and higher).
        ///•	To properly view and use this form, your internet browser will need to support HTML5. It&apos;s recommended that your computer have the latest version of one of the more widely used internet web browsers.
        ///•	You can navigate the form using any mobile device (such as a tablet or a smart phone). The information displayed will be adapted for your device.
        ///•	No [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BottomBody {
            get {
                return ResourceManager.GetString("BottomBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Specifications.
        /// </summary>
        internal static string TechnicalSpecs {
            get {
                return ResourceManager.GetString("TechnicalSpecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the XML Product Monograph (PM) Web Form.
        /// </summary>
        internal static string UsingXMLPM {
            get {
                return ResourceManager.GetString("UsingXMLPM", resourceCulture);
            }
        }
    }
}
